# Generated by Django 4.1.7 on 2023-04-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledgearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledgearea', models.CharField(db_column='knowledgeArea', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'KNOWLEDGEAREA',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=255, null=True, unique=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('schedulepath', models.CharField(blank=True, db_column='schedulePath', max_length=1023, null=True, unique=True)),
                ('knowledgearea', models.ForeignKey(blank=True, db_column='KNOWLEDGEAREA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.knowledgearea')),
            ],
            options={
                'db_table': 'TEACHERS',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('teacherid', models.OneToOneField(db_column='teacherId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teachers.teachers')),
                ('subjectcode', models.ForeignKey(db_column='subjectCode', on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
            ],
            options={
                'db_table': 'TEACHING',
                'unique_together': {('teacherid', 'subjectcode')},
            },
        ),
    ]
