# Generated by Django 4.2 on 2023-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringhour',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='tutoringhour',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='friday',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='monday',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='thursday',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='tuesday',
            field=models.CharField(default=4, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='wednesday',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutoringhour',
            name='day',
            field=models.CharField(max_length=30),
        ),
    ]
