# Generated by Django 4.2 on 2023-04-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_teachers_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='knowledgearea',
            table='knowledgearea',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
