# Generated by Django 4.2 on 2023-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_tutoringhour_ending_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringhour',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='tutoringhour',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='tutoringhour',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='tutoringhour',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='tutoringhour',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='ending_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringhour',
            name='start_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutoringhour',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')]),
        ),
    ]
