# Generated by Django 4.2 on 2023-04-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_coordinator_and_more'),
        ('teachers', '0004_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringhour',
            name='subject_id',
            field=models.ForeignKey(default=40951, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_hours', to='subjects.subject'),
            preserve_default=False,
        ),
    ]
