# Generated by Django 4.2 on 2023-04-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teaching_options_remove_teacher_knowledgearea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaching',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='knowledgearea',
            name='knowledgearea',
        ),
        migrations.AddField(
            model_name='knowledgearea',
            name='knowledge_area',
            field=models.CharField(default='Desarrollo Software', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='knowledge_area',
            field=models.ForeignKey(db_column='knowledge_area', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='teachers.knowledgearea'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='knowledgearea',
            table='knowledge_area',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
        migrations.AlterModelTable(
            name='teaching',
            table='teaching',
        ),
        migrations.CreateModel(
            name='tutoringHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('start_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoringHours', to='teachers.teacher')),
            ],
            options={
                'db_table': 'tutoring_hour',
            },
        ),
    ]
