# Generated by Django 4.2 on 2023-04-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teaching_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='office',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutoringhour',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_hours', to='teachers.teacher'),
        ),
        migrations.DeleteModel(
            name='Teaching',
        ),
    ]
