# Generated by Django 4.2 on 2023-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_tutoringhour_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringhour',
            name='subject_id',
        ),
    ]
