# Generated by Django 4.2 on 2023-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_office_alter_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringhour',
            name='day',
            field=models.CharField(max_length=30),
        ),
    ]
