# Generated by Django 4.2 on 2023-04-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectschedules',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subjectschedules',
            name='groupcode',
        ),
        migrations.RemoveField(
            model_name='subjectschedules',
            name='subjectcode',
        ),
        migrations.DeleteModel(
            name='Userschedules',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Subjectschedules',
        ),
    ]
