# Generated by Django 4.2 on 2023-04-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedules',
            name='schedulepath',
        ),
    ]
