# Generated by Django 4.2 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_subjectschedules_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='horario 1', max_length=30),
            preserve_default=False,
        ),
    ]
