# Generated by Django 4.2 on 2023-04-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedules.schedule'),
            preserve_default=False,
        ),
    ]
