# Generated by Django 4.2 on 2023-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_schedule_events_event_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='subject_code',
            field=models.IntegerField(default=40951, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
