# Generated by Django 4.2 on 2023-04-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_event_id_event_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='subject_code',
            field=models.IntegerField(),
        ),
    ]
