# Generated by Django 4.2 on 2023-05-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_rename_days_of_week_event_daysofweek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='daysOfWeek',
            new_name='days_of_week',
        ),
    ]
