# Generated by Django 4.2 on 2023-05-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_rename_daysofweek_event_days_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='events',
            field=models.ManyToManyField(to='schedules.event'),
        ),
    ]
