# Generated by Django 4.2 on 2023-05-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedules.schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
