# Generated by Django 4.2 on 2023-05-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_remove_schedule_events_event_schedule_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='backgroundColor',
            field=models.CharField(default='#FEAD57', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#FEAD57', max_length=255),
        ),
    ]
