# Generated by Django 4.1.7 on 2023-04-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'DEGREE',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=1)),
                ('linkpd', models.CharField(db_column='linkPD', max_length=1023)),
                ('type', models.CharField(max_length=14)),
                ('semester', models.CharField(max_length=7)),
                ('degree', models.ForeignKey(db_column='degree', on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.degree')),
            ],
            options={
                'db_table': 'SUBJECTS',
            },
        ),
        migrations.CreateModel(
            name='SubjectDepartment',
            fields=[
                ('subjectcode', models.OneToOneField(db_column='subjectCode', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='subjects.subject')),
                ('department', models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.department')),
            ],
            options={
                'db_table': 'SUBJECTDEPARTMENTS',
                'unique_together': {('subjectcode', 'department')},
            },
        ),
    ]
