# Generated by Django 4.2 on 2023-04-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_phone_number'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coordinator',
            field=models.ForeignKey(db_column='id', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('subject', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='group',
        ),
    ]
