# Generated by Django 4.2 on 2023-04-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='type',
            new_name='subject_type',
        ),
        migrations.AddField(
            model_name='department',
            name='subjects',
            field=models.ManyToManyField(related_name='departments', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='degree',
            field=models.ForeignKey(db_column='degree', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='subjects.degree'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='linkpd',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterModelTable(
            name='degree',
            table='degree',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.DeleteModel(
            name='SubjectDepartment',
        ),
    ]
