# Generated by Django 4.2 on 2023-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_type_subject_subject_type_department_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(max_length=30),
        ),
    ]
