# Generated by Django 4.2 on 2023-04-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_semester_alter_subject_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='degree',
        ),
    ]
