# Generated by Django 4.2 on 2023-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_subject_degree'),
        ('subjects', '0005_remove_subject_teachers_delete_subjectteacher'),
    ]

    operations = [
    ]
