# Generated by Django 4.2 on 2023-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subjectteacher_delete_degree_subject_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
    ]
