# Generated by Django 4.2 on 2023-04-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='degree',
            field=models.ForeignKey(db_column='degree', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='subjects.degree'),
        ),
    ]
