# Generated by Django 4.2 on 2023-04-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_lesson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subjectteacher',
            table='subject_teacher',
        ),
    ]
