# Generated by Django 4.2 on 2023-04-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_office_alter_teacher_phone_number_and_more'),
        ('subjects', '0013_alter_subjectteacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_in_subject', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_of_teacher', to='teachers.teacher'),
        ),
    ]
