# Generated by Django 4.2 on 2023-04-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_alter_subjectteacher_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(default='Informatica y sistemas', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
